run:
  # Timeout for analysis
  timeout: 5m
  # Include test files
  tests: true

linters-settings:
  govet:
    # Enable recommended checks
    enable-all: true
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - whyNoLint
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  # Explicitly enable key linters
  enable:
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - bodyclose
  # Disable deprecated or overly strict linters
  disable:
    - govet  # Too noisy

issues:
  # Exclude rules for test files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - revive
      text: "unused-parameter"
      path: _test\.go

  # Limit issue reporting
  max-issues-per-linter: 0
  max-same-issues: 0

  # # Only show new issues compared to previous commit
  # new-from-rev: HEAD~1
