---
version: "1.0"
# Configuration for comprehensive scanning of ALL untagged resources

aws:
  regions:
    mode: specific
    list:
      - us-east-1
  batch_size: 100  # Large batch size for thorough scanning

global:
  enabled: true
  tag_criteria:
    minimum_required_tags: 1  # Explicitly set to 1 to catch ANY untagged resource
    required_tags:
      - Name  # Minimal tag requirement
    compliance_level: high

resources:
  # Enable scanning for all major resource types
  s3:
    enabled: true
    tag_criteria:
      minimum_required_tags: 1
      required_tags:
        - Name
      compliance_level: high

  ec2:
    enabled: true
    tag_criteria:
      minimum_required_tags: 1
      required_tags:
        - Name
      compliance_level: high

# Simplified compliance levels
compliance_levels:
  high:
    required_tags:
      - Name
    specific_tags:
      ComplianceStatus: "untagged-detected"

# Minimal tag validation
tag_validation:
  case_sensitivity:
    Name:
      mode: strict
    ComplianceStatus:
      mode: strict

  pattern_rules:
    Name: ^.+$  # Ensure Name tag is not empty
  case_rules:
    Name:
      case: lowercase
      message: "Name tag must be lowercase"
    ComplianceStatus:
      case: lowercase
      message: "ComplianceStatus tag must be lowercase"

# Notification configuration
notifications:
  slack:
    enabled: true
    channels:
      high_priority: "untagged-resources-alert"
  email:
    enabled: true
    recipients:
      - cloud-team@company.com
    frequency: daily
