---
name: Issue Comment Created

on:
  issue_comment:
    types: [created]

jobs:
  comment-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment;
            const issue = context.payload.issue;

            if (comment.body.includes('/reopen')) {
              if (issue.state === 'closed') {
                github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'open'
                });
              }
            }
